/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;


import BUS.CTKhuyenMai_BUS;
import BUS.SanPham_BUS;
import DTO.CTKhuyenMai_DTO;
import DTO.SanPham_DTO;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import static java.awt.Frame.NORMAL;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import static java.lang.Float.parseFloat;
import java.util.List;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author blemb
 */
public class BanHang_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form BangHang_UI
     */

    DefaultTableModel model = new DefaultTableModel();

    public BanHang_GUI() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        
        showAll();
        
    }
    public void showAll(){
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btn_inhoadon = new javax.swing.JButton();
        btn_thanhtoan = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        txt_soluong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_chon = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_tongtien = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dachon = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_giavi = new javax.swing.JButton();
        btn_donglanh = new javax.swing.JButton();
        btn_rau = new javax.swing.JButton();
        btn_thit = new javax.swing.JButton();
        btn_luongthuc = new javax.swing.JButton();
        btn_mitom = new javax.swing.JButton();
        btn_khac = new javax.swing.JButton();
        btn_bia = new javax.swing.JButton();
        btn_banhkeo = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1050, 570));
        setPreferredSize(new java.awt.Dimension(1060, 580));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 339, 80, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tùy chọn"));

        btn_inhoadon.setText("In hóa đơn");
        btn_inhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inhoadonActionPerformed(evt);
            }
        });

        btn_thanhtoan.setText("Thanh toán");
        btn_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhtoanActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa ");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        txt_soluong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_soluong.setText("1");

        jLabel1.setText("Số lượng:");

        btn_chon.setText("Chọn");
        btn_chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        jLabel2.setText("Tổng tiền:");

        lb_tongtien.setBackground(new java.awt.Color(255, 255, 0));
        lb_tongtien.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_tongtien.setText("VND");
        lb_tongtien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lb_tongtien.setName(""); // NOI18N
        lb_tongtien.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_thanhtoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_inhoadon)
                        .addGap(49, 49, 49)
                        .addComponent(btn_refresh)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_chon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_chon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_tongtien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_inhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_refresh, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 257, 370, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản phẩm"));

        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "Mô tả", "Đơn giá", "Số lượng", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(tbl_sanpham);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 658, 300));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Đã chọn"));

        tbl_dachon.setBackground(new java.awt.Color(255, 255, 0));
        tbl_dachon.setForeground(new java.awt.Color(255, 51, 102));
        tbl_dachon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số lượng", "Đơn giá", "Giá KM", "Tổng cộng"
            }
        ));
        jScrollPane1.setViewportView(tbl_dachon);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại sản phẩm"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_giavi.setText("Gia vị");
        btn_giavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaviActionPerformed(evt);
            }
        });
        jPanel2.add(btn_giavi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 83, 49));

        btn_donglanh.setText("Đông lạnh");
        btn_donglanh.setAutoscrolls(true);
        btn_donglanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donglanhActionPerformed(evt);
            }
        });
        jPanel2.add(btn_donglanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 96, 90, 49));

        btn_rau.setText("Rau củ, trái cây");
        btn_rau.setAutoscrolls(true);
        btn_rau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_rau.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_rau.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btn_rau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rauActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rau, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 28, 90, 50));

        btn_thit.setText("Thịt, Trứng");
        btn_thit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 50));

        btn_luongthuc.setText("Lương thực");
        btn_luongthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luongthucActionPerformed(evt);
            }
        });
        jPanel2.add(btn_luongthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 108, 49));

        btn_mitom.setText("Mì, miếng, phở, cháo");
        btn_mitom.setAutoscrolls(true);
        btn_mitom.setFocusTraversalPolicyProvider(true);
        btn_mitom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_mitom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mitomActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mitom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 108, 49));

        btn_khac.setText("Khác...");
        btn_khac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khacActionPerformed(evt);
            }
        });
        jPanel2.add(btn_khac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 108, 53));

        btn_bia.setText("Bia, nước ngọt");
        btn_bia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_biaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_bia, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 163, 90, 53));

        btn_banhkeo.setText("Bánh kẹo");
        btn_banhkeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_banhkeoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_banhkeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 83, 53));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 370, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rauActionPerformed
        // TODO add your handling code here:

        new SanPham_BUS().docSanPham_loai("1");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_rauActionPerformed

    private void btn_thitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thitActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("6");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_thitActionPerformed

    private void btn_donglanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donglanhActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("7");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_donglanhActionPerformed
     
    private void btn_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhtoanActionPerformed
        // TODO add your handling code here:
        int i = model.getRowCount();
        if(i != 0){
        for(int j = i-1; j >= 0; j--){
            String soluong1 = String.valueOf(Math.round(parseFloat(model.getValueAt(j, 3).toString())));           
            String maSp = model.getValueAt(j, 1).toString();
            new SanPham_BUS().capNhatSlSp(soluong1, maSp);         
            model.removeRow(j);
        }
        showAll();
        JOptionPane.showMessageDialog(null, "Mua sản phẩm thành công !");
        inHoaDon();
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sản phẩm !");
        }
    }//GEN-LAST:event_btn_thanhtoanActionPerformed

    private void btn_chonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonActionPerformed
        // TODO add your handling code here:
        //Nhớ đổi Giá data base thành Int
        int index = 0;
        int flag = 0;
        int flag1 = 0;
        float soLuong = parseFloat(txt_soluong.getText());
        int i = tbl_sanpham.getSelectedRow();
       int count_row = model.getRowCount();

       new CTKhuyenMai_BUS().docDS_CTKM();
       float gia_km = (float) 0.0;

       for(CTKhuyenMai_DTO km : CTKhuyenMai_BUS.ds_ctkm){
           if( tbl_sanpham.getValueAt(i, 1).toString().equals(km.id_sp)){
               gia_km = (float) (parseFloat((km.giamcon)));
               flag1 = 1;
           }
       }

        Vector header = new Vector();
            header.add("STT");
            header.add("Mã SP");
            header.add("Tên SP");
            header.add("Số lượng");
            header.add("Đơn giá");
            header.add("Giá KM");
            header.add("Tổng cộng");
            if(model.getRowCount() == 0)
            model = new DefaultTableModel(header,0);

            //Cập nhật số lượng (trùng mã sp)

            String a = tbl_sanpham.getValueAt(i, 1).toString();
            if(count_row > 0){
            for(int j = 0; j < count_row; j++){
                //kiem tra ID trùng
            String b = model.getValueAt(j, 1).toString();
                if(b.equals(a)){
                    index = j;
                    flag = 1;
                }
            }           
            }
            //Kiem tra SP co khuyen mai


            //nếu sp chưa có trên model
            float dongia = parseFloat(tbl_sanpham.getModel().getValueAt(i, 6).toString());

            if(flag == 0){

                Vector row = new Vector();
            row.add(count_row++);
            row.add(tbl_sanpham.getModel().getValueAt(i, 1));
            row.add(tbl_sanpham.getModel().getValueAt(i, 4));
            row.add(txt_soluong.getText());
            row.add(dongia);
            //Neu co khuyen mai thi add giá km, khong co thi add rỗng

            if(flag1 == 1){
                row.add(gia_km);
                row.add(gia_km*soLuong);
            } else {
                row.add("");
                row.add(dongia*soLuong);
            }
            //so sánh lúc chọn 
                if(parseFloat(txt_soluong.getText()) <= parseFloat(tbl_sanpham.getModel().getValueAt(i, 7).toString()) && parseFloat(txt_soluong.getText()) > 0){
                model.addRow(row);
                tbl_dachon.setModel(model);
                } else {
                    JOptionPane.showMessageDialog(null, "Số lượng không còn đủ trong kho");
                }
            }
            //Nếu sp có ở model rồi
            else {

                Vector row = new Vector();
                row.add(model.getValueAt(index, 0));
            row.add(tbl_sanpham.getModel().getValueAt(i, 1));
            row.add(tbl_sanpham.getModel().getValueAt(i, 4));
            //Cập nhật số lượng và giá sản phẩm đã chọn
            row.add(parseFloat(txt_soluong.getText()) + parseFloat(model.getValueAt(index, 3).toString()));
            row.add(dongia);
            //Neu co khuyen mai thi add giá km, khong co thi add rỗng
            if(flag1 == 1){
               row.add(gia_km);
               row.add((gia_km)*soLuong + parseFloat(model.getValueAt(index, 3).toString())*gia_km);
            } else {
               row.add("");
               row.add(dongia*soLuong + dongia*parseFloat(model.getValueAt(index, 3).toString()));

            }


            //so sánh lúc chọn (sp đã có trên model)
            float SoLuongDangChon = parseFloat(txt_soluong.getText()) + parseFloat(model.getValueAt(index, 3).toString());
            //kiem tra khuyen mai

            if(SoLuongDangChon <= parseFloat(tbl_sanpham.getModel().getValueAt(i, 7).toString()) && parseFloat(txt_soluong.getText()) > 0){
                model.removeRow(index);
                model.insertRow(index, row);
                tbl_dachon.setModel(model);   
                } else {
                    JOptionPane.showMessageDialog(null, "Số lượng không còn đủ trong kho");
                }

            }
            float tongtien = 0;
            for(int j = 0; j < tbl_dachon.getRowCount(); j++){

                tongtien += parseFloat(tbl_dachon.getValueAt(j, 6).toString());
                lb_tongtien.setText(String.valueOf(tongtien) + "VND");
            }
    }//GEN-LAST:event_btn_chonActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int i = tbl_dachon.getSelectedRow();
        if(parseInt(txt_soluong.getText()) >= parseFloat(tbl_dachon.getModel().getValueAt(i, 3).toString())){
            model.removeRow(i);
        for(int j = 0; j < model.getRowCount(); j++ ){
            model.setValueAt(j, j, 0);
        }
        } else {
            float a = parseFloat(tbl_dachon.getValueAt(i, 3).toString());
            float b = parseFloat(txt_soluong.getText());
            tbl_dachon.setValueAt(a - b, i, 3);
            model.setValueAt(a - b, i, 3);
            tbl_dachon.setModel(model);
        }
        
        
        tbl_dachon.setModel(model);
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        showAll();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_luongthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luongthucActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("8");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_luongthucActionPerformed

    private void btn_giaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaviActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("9");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_giaviActionPerformed

    private void btn_mitomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mitomActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("10");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_mitomActionPerformed

    private void btn_biaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_biaActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("11");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_biaActionPerformed

    private void btn_banhkeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_banhkeoActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("12");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_banhkeoActionPerformed

    private void btn_khacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khacActionPerformed
        // TODO add your handling code here:
        new SanPham_BUS().docSanPham_loai("13");
        DefaultTableModel n = new DefaultTableModel();
        SanPham_BUS bus = new SanPham_BUS();
        bus.docSanPham();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_SanPham");
            header.add("Loại");
            header.add("Ncc");
            header.add("Tên SP");
            header.add("Mô tả");
            header.add("Đơn giá");
            header.add("Số lượng");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (SanPham_DTO sp : SanPham_BUS.dssp_loai) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(sp.id_sanpham);
            row.add(sp.id_loai);
            row.add(sp.id_ncc);
            row.add(sp.tensp);
            row.add(sp.mota);
            row.add(sp.giaban);
            row.add(sp.soluong);
            n.addRow(row);
            k++;
        }
        tbl_sanpham.setModel(n);
    }//GEN-LAST:event_btn_khacActionPerformed
    int k = 0;
    public void inHoaDon(){
        k++;
        String path="D:\\";
        JFileChooser j = new JFileChooser();
        /*j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if(x == JFileChooser.APPROVE_OPTION){
            path = j.getSelectedFile().getPath();
        }*/

        Document doc = new Document();
        doc.addTitle("HÓA ĐƠN");
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"Hoadon" + k +".pdf"));
            BaseFont bf = BaseFont.createFont("c:\\windows\\fonts\\times.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font font10 = new Font(bf, 10, Font.NORMAL);



            doc.open();

            PdfPTable tbl = new PdfPTable(7);
            //header
            Paragraph pa7 = new Paragraph("STT", font10);
            tbl.addCell(pa7);
            Paragraph pa8 = new Paragraph("Mã SP", font10);
            tbl.addCell(pa8);
            Paragraph pa9 = new Paragraph("Tên SP", font10);
            tbl.addCell(pa9);
            Paragraph pa10 = new Paragraph("Số lượng", font10);
            tbl.addCell(pa10);
            Paragraph pa11 = new Paragraph("Đơn giá", font10);
            tbl.addCell(pa11);
            Paragraph pa12 = new Paragraph("Giá KM", font10);
            tbl.addCell(pa12);
            Paragraph pa13 = new Paragraph("Tổng cộng", font10);
            tbl.addCell(pa13);
            String tong = lb_tongtien.getText();
            for(int i = 0; i < tbl_dachon.getRowCount(); i++){



                String stt = tbl_dachon.getValueAt(i, 0).toString();
                Paragraph pa1 = new Paragraph(stt, font10);
                String ma_sp = tbl_dachon.getValueAt(i, 1).toString();
                Paragraph pa2 = new Paragraph(ma_sp, font10);
                String ten_sp = tbl_dachon.getValueAt(i, 2).toString();
                Paragraph pa3 = new Paragraph(ten_sp, font10);
                String soluong = tbl_dachon.getValueAt(i, 3).toString();
                Paragraph pa4 = new Paragraph(soluong, font10);
                String don_gia = tbl_dachon.getValueAt(i, 4).toString();
                Paragraph pa5 = new Paragraph(don_gia, font10);
                String gia_km = tbl_dachon.getValueAt(i, 5).toString();
                Paragraph pa14 = new Paragraph(gia_km, font10);
                String tongcong = tbl_dachon.getValueAt(i, 6).toString();
                Paragraph pa15 = new Paragraph(tongcong, font10);
                tbl.addCell(pa1);
                tbl.addCell(pa2);
                tbl.addCell(pa3);
                tbl.addCell(pa4);
                tbl.addCell(pa5);
                tbl.addCell(pa14);
                tbl.addCell(pa15);
            }
                tbl.addCell("");
                tbl.addCell("");
                tbl.addCell("");
                tbl.addCell("");
                tbl.addCell("");
                Paragraph pa6 = new Paragraph("Tổng tiền", font10);
                tbl.addCell(pa6);
                tbl.addCell(tong);
            doc.add(tbl);

                    } catch (FileNotFoundException ex) {
            Logger.getLogger(BanHang_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(BanHang_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }
    private void btn_inhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inhoadonActionPerformed
        // TODO add your handling code here:
        inHoaDon();
    }//GEN-LAST:event_btn_inhoadonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_banhkeo;
    private javax.swing.JButton btn_bia;
    private javax.swing.JButton btn_chon;
    private javax.swing.JButton btn_donglanh;
    private javax.swing.JButton btn_giavi;
    private javax.swing.JButton btn_inhoadon;
    private javax.swing.JButton btn_khac;
    private javax.swing.JButton btn_luongthuc;
    private javax.swing.JButton btn_mitom;
    private javax.swing.JButton btn_rau;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_thanhtoan;
    private javax.swing.JButton btn_thit;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_tongtien;
    private javax.swing.JTable tbl_dachon;
    private javax.swing.JTable tbl_sanpham;
    private javax.swing.JTextField txt_soluong;
    // End of variables declaration//GEN-END:variables
}
