/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.DangKi_BUS;
import BUS.NhanVien_BUS;
import BUS.SanPham_BUS;
import DTO.SanPham_DTO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author blemb
 */
public class DangKi_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DangKi_GUI
     */
    public DangKi_GUI() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setMinimumSize(new Dimension(830, 556));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_reverse_passwrd = new javax.swing.JPasswordField();
        TitileMatKhau1 = new javax.swing.JLabel();
        btn_dangKi = new javax.swing.JButton();
        lb_exit_login = new javax.swing.JLabel();
        TitleTenDangNhap = new javax.swing.JLabel();
        TenDangNhapTxt = new javax.swing.JTextField();
        txt_passwrd = new javax.swing.JPasswordField();
        TitileMatKhau = new javax.swing.JLabel();
        TieuDe = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_reverse_passwrd.setText("123");
        txt_reverse_passwrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_reverse_passwrdMouseClicked(evt);
            }
        });
        txt_reverse_passwrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_reverse_passwrdActionPerformed(evt);
            }
        });
        txt_reverse_passwrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_reverse_passwrdKeyPressed(evt);
            }
        });
        getContentPane().add(txt_reverse_passwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 200, 40));

        TitileMatKhau1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitileMatKhau1.setText("Nhập lại mật khẩu");
        getContentPane().add(TitileMatKhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        btn_dangKi.setText("Đăng kí");
        btn_dangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangKiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 200, 30));

        lb_exit_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close-button (1).png"))); // NOI18N
        lb_exit_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exit_loginMouseClicked(evt);
            }
        });
        getContentPane().add(lb_exit_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 30));

        TitleTenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleTenDangNhap.setText("Tên đăng nhập");
        getContentPane().add(TitleTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        TenDangNhapTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TenDangNhapTxt.setText("nhanvien1");
        TenDangNhapTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenDangNhapTxtActionPerformed(evt);
            }
        });
        TenDangNhapTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TenDangNhapTxtKeyPressed(evt);
            }
        });
        getContentPane().add(TenDangNhapTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 200, 40));

        txt_passwrd.setText("123");
        txt_passwrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwrdMouseClicked(evt);
            }
        });
        txt_passwrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwrdActionPerformed(evt);
            }
        });
        txt_passwrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwrdKeyPressed(evt);
            }
        });
        getContentPane().add(txt_passwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 200, 40));

        TitileMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitileMatKhau.setText("Mật khẩu");
        getContentPane().add(TitileMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        TieuDe.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        TieuDe.setText("ĐĂNG KÍ TÀI KHOẢN");
        getContentPane().add(TieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-login.jpg"))); // NOI18N
        BackGround.setName(""); // NOI18N
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_reverse_passwrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_reverse_passwrdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_reverse_passwrdMouseClicked

    private void txt_reverse_passwrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_reverse_passwrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_reverse_passwrdActionPerformed

    private void txt_reverse_passwrdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_reverse_passwrdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_reverse_passwrdKeyPressed

    private void btn_dangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangKiActionPerformed
        // TODO add your handling code here:
        String tenDN = TenDangNhapTxt.getText();
        String matKhau = txt_passwrd.getText();
        String nhaplai_Mk = txt_reverse_passwrd.getText();
        String Email = "null@gamil.com";
        String HoVaTen = "null";
        String DiaChi = "null";
        String SoDienThoai = "null";
        NhanVien_BUS nv = new NhanVien_BUS();
        DangKi_BUS dk = new DangKi_BUS();
        if(dk.check_passwrd(matKhau, nhaplai_Mk)){           
            if(nv.them_NhanVien(tenDN, matKhau, HoVaTen, DiaChi, Email, SoDienThoai)){           
                JOptionPane.showMessageDialog(rootPane, "Đăng kí thành công"); 
                DangNhap_GUI dn = new DangNhap_GUI();
                dn.setVisible(true);
                this.dispose();
            }
            else 
                JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập đã tồn tại");       
        } else JOptionPane.showMessageDialog(rootPane, "Mật khẩu không khớp");
        
        
    }//GEN-LAST:event_btn_dangKiActionPerformed

    private void lb_exit_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exit_loginMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lb_exit_loginMouseClicked

    private void TenDangNhapTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenDangNhapTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenDangNhapTxtActionPerformed

    private void TenDangNhapTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TenDangNhapTxtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btn_dangKi.doClick();
        }
    }//GEN-LAST:event_TenDangNhapTxtKeyPressed

    private void txt_passwrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwrdMouseClicked
        // TODO add your handling code here:
        txt_passwrd.setText("");
    }//GEN-LAST:event_txt_passwrdMouseClicked

    private void txt_passwrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwrdActionPerformed

    private void txt_passwrdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwrdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btn_dangKi.doClick();
        }
    }//GEN-LAST:event_txt_passwrdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKi_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    public static javax.swing.JTextField TenDangNhapTxt;
    private javax.swing.JLabel TieuDe;
    private javax.swing.JLabel TitileMatKhau;
    private javax.swing.JLabel TitileMatKhau1;
    private javax.swing.JLabel TitleTenDangNhap;
    private javax.swing.JButton btn_dangKi;
    private javax.swing.JLabel lb_exit_login;
    private javax.swing.JPasswordField txt_passwrd;
    private javax.swing.JPasswordField txt_reverse_passwrd;
    // End of variables declaration//GEN-END:variables
}
