/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;


import BUS.KhuyenMai_BUS;
import BUS.SanPham_BUS;
import DTO.KhuyenMai_DTO;
import DTO.SanPham_DTO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import BUS.CTKhuyenMai_BUS;
import DTO.CTKhuyenMai_DTO;

/**
 *
 * @author blemb
 */
public class KhuyenMai_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form KhuyenMai_GUI
     */
    public KhuyenMai_GUI() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        showAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Timkiem = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khuyenmai = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_batdau = new javax.swing.JTextField();
        txt_makm = new javax.swing.JTextField();
        txt_tenkm = new javax.swing.JTextField();
        txt_ketthuc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtn_khoangtg = new javax.swing.JRadioButton();
        rbtn_ma = new javax.swing.JRadioButton();
        rbtn_ten = new javax.swing.JRadioButton();
        rbtn_ngaybd = new javax.swing.JRadioButton();
        rbtn_ngaykt = new javax.swing.JRadioButton();
        txt_timkiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_ngaybd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ngaykt = new javax.swing.JTextField();
        btn_lammoi = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        ttkm_gtkm1 = new javax.swing.JTextField();
        ttkm_makm4 = new javax.swing.JTextField();
        ttkm_masp1 = new javax.swing.JTextField();
        txt_ketthuc2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ttkm_makm5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ttkm_makm6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ttkm_makm7 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ctkhuyenmai1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1075, 600));
        setMinimumSize(new java.awt.Dimension(1075, 600));
        setPreferredSize(new java.awt.Dimension(1075, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setMaximumSize(new java.awt.Dimension(1075, 590));
        jPanel6.setMinimumSize(new java.awt.Dimension(1075, 590));
        jPanel6.setPreferredSize(new java.awt.Dimension(1075, 590));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Khuyến mãi"));

        tbl_khuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KM", "Tên KM", "Bắt đầu", "Kết thúc"
            }
        ));
        tbl_khuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khuyenmai);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 420, 340));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Khuyến mãi"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_batdau.setColumns(10);
        txt_batdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_batdauActionPerformed(evt);
            }
        });
        jPanel3.add(txt_batdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 109, -1));

        txt_makm.setColumns(3);
        jPanel3.add(txt_makm, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 24, -1, -1));

        txt_tenkm.setColumns(10);
        jPanel3.add(txt_tenkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 380, -1));

        txt_ketthuc.setColumns(10);
        txt_ketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ketthucActionPerformed(evt);
            }
        });
        jPanel3.add(txt_ketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 115, -1));

        jLabel2.setText("Tên KM:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Mã KM:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 27, -1, -1));

        jLabel4.setText("Bắt đầu:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setText("Kết thúc:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 466, 632, 138));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        Timkiem.add(rbtn_khoangtg);
        rbtn_khoangtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_khoangtgActionPerformed(evt);
            }
        });

        Timkiem.add(rbtn_ma);
        rbtn_ma.setText("Theo mã");

        Timkiem.add(rbtn_ten);
        rbtn_ten.setText("Theo Tên");

        Timkiem.add(rbtn_ngaybd);
        rbtn_ngaybd.setText("Ngày bắt đầu");

        Timkiem.add(rbtn_ngaykt);
        rbtn_ngaykt.setText("Ngày kết thúc");

        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ:");

        jLabel6.setText("Đến:");

        btn_lammoi.setText("Refresh");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtn_khoangtg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_ngaykt))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_timkiem)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn_ten)
                                .addGap(148, 148, 148)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtn_ngaykt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn_ma, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtn_ngaybd)
                        .addGap(131, 131, 131))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_lammoi)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_ma)
                    .addComponent(rbtn_ten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtn_ngaykt)
                    .addComponent(rbtn_ngaybd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn_khoangtg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txt_ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btn_lammoi)
                .addGap(20, 20, 20))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 6, -1, 240));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết khuyến mãi"));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ttkm_gtkm1.setColumns(10);
        ttkm_gtkm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttkm_gtkm1ActionPerformed(evt);
            }
        });
        jPanel11.add(ttkm_gtkm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 76, 109, -1));

        ttkm_makm4.setColumns(3);
        jPanel11.add(ttkm_makm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 24, -1, -1));

        ttkm_masp1.setColumns(10);
        jPanel11.add(ttkm_masp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 347, 20));

        txt_ketthuc2.setColumns(10);
        txt_ketthuc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ketthuc2ActionPerformed(evt);
            }
        });
        jPanel11.add(txt_ketthuc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 115, -1));

        jLabel16.setText("Tên SP:");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 20));

        jLabel17.setText("Mã KM:");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, -1, -1));

        jLabel18.setText("Bắt đầu:");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 79, -1, -1));

        jLabel19.setText("Kết thúc:");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel20.setText("Mã KM:");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        ttkm_makm5.setColumns(3);
        jPanel11.add(ttkm_makm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel21.setText("Mã KM:");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        ttkm_makm6.setColumns(3);
        jPanel11.add(ttkm_makm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabel22.setText("Mã KM:");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        ttkm_makm7.setColumns(3);
        jPanel11.add(ttkm_makm7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 632, 200));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết khuyến mãi"));

        tbl_ctkhuyenmai1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID_KM", "ID_SP", "Tên SP", "KM (%)", "Đơn giá", "Giảm còn"
            }
        ));
        tbl_ctkhuyenmai1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ctkhuyenmai1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_ctkhuyenmai1);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txt_batdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_batdauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_batdauActionPerformed

    private void txt_ketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ketthucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ketthucActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        showAll();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void tbl_khuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khuyenmaiMouseClicked
        // TODO add your handling code here:
        int i = tbl_khuyenmai.getSelectedRow();
        txt_makm.setText(tbl_khuyenmai.getModel().getValueAt(i, 1).toString());
        txt_tenkm.setText(tbl_khuyenmai.getModel().getValueAt(i,2).toString());
        txt_batdau.setText(tbl_khuyenmai.getModel().getValueAt(i,3).toString());
        txt_ketthuc.setText(tbl_khuyenmai.getModel().getValueAt(i,4).toString());
        
    }//GEN-LAST:event_tbl_khuyenmaiMouseClicked

    private void rbtn_khoangtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_khoangtgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_khoangtgActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String a = txt_makm.getText();
        String b = txt_tenkm.getText();
        String c = txt_batdau.getText();
        String d = txt_ketthuc.getText();
        String e = "";
        int flag = 0;
        if("".equals(a) || "".equals(b) || "".equals(c) || "".equals(d) ){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        } else {
            for(int i = 0; i < tbl_khuyenmai.getRowCount(); i++){
                if(a.equals(tbl_khuyenmai.getValueAt(i, 1)))
                    flag = 1;
            }
            if(flag != 1){
            new KhuyenMai_BUS().themKM(a, b, c, d);
            } else {
                JOptionPane.showMessageDialog(null, "Mã khuyến mãi bị trùng");
            }
        }
        showAll();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int i = tbl_khuyenmai.getSelectedRow();
        String id = tbl_khuyenmai.getValueAt(i, 1).toString();
        new KhuyenMai_BUS().xoaKM(id);
        showAll();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        //lỗi refresh
        int flag = 0;
        int i = tbl_khuyenmai.getSelectedRow();
        String id = tbl_khuyenmai.getValueAt(i, 1).toString();
        String id_new = txt_makm.getText();
        String ten = txt_tenkm.getText();
        String batdau = txt_batdau.getText();
        String ketthuc = txt_ketthuc.getText();
        for(int j = 0; j < tbl_khuyenmai.getRowCount(); j++){
            if(j != i){
                if(id_new.equals(tbl_khuyenmai.getValueAt(j, 1))){
                    flag = 1;
                }
            }
        }
        if(flag != 1){
        new KhuyenMai_BUS().suaKM(id_new, ten, batdau, ketthuc, id);
        
        }
        else JOptionPane.showMessageDialog(null, "Mã khuyến mãi đã tồn tại");
    }//GEN-LAST:event_btn_suaActionPerformed
    
    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String key_word = txt_timkiem.getText();
        if(rbtn_ten.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ten(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
        
        if(rbtn_ma.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ma(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
        if(rbtn_ngaybd.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ngaybd(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
        if(rbtn_ngaykt.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ngaykt(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }      
        if(rbtn_khoangtg.isSelected()){
            String bd = txt_ngaybd.getText();
            String kt = txt_ngaykt.getText();
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_khoangtg(bd, kt); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void ttkm_gtkm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttkm_gtkm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttkm_gtkm1ActionPerformed

    private void txt_ketthuc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ketthuc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ketthuc2ActionPerformed

    private void tbl_ctkhuyenmai1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ctkhuyenmai1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_ctkhuyenmai1MouseClicked
    public void showAll(){
        DefaultTableModel n = new DefaultTableModel();
        KhuyenMai_BUS bus = new KhuyenMai_BUS();
        bus.docDSKM();
        Vector header = new Vector();
            header.add("STT");
            header.add("Mã KM");
            header.add("Tên KM");
            header.add("Bắt đầu");
            header.add("Kết thúc");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (KhuyenMai_DTO km :  KhuyenMai_BUS.dskm) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            n.addRow(row);
            k++;
        }
        tbl_khuyenmai.setModel(n);
    }
    public void showAll_ctkm(){
        DefaultTableModel n = new DefaultTableModel();
        CTKhuyenMai_BUS bus = new CTKhuyenMai_BUS();
        bus.docDS_CTKM();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_KM");
            header.add("ID_SP");
            header.add("Tên SP");
            header.add("KM (%)");
            header.add("Đơn giá");
            header.add("Giá sau KM");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (CTKhuyenMai_DTO ctkm : CTKhuyenMai_BUS.ds_ctkm) {

            Vector row = new Vector();
            row.add(k);
            row.add(ctkm.id_km);
            row.add(ctkm.id_sp);
            row.add(ctkm.ten_sp);
            row.add(ctkm.gtkm);
            row.add(ctkm.giaban);
            row.add(ctkm.giamcon);
            n.addRow(row);
            k++;
        }
        tbl_ctkhuyenmai.setModel(n);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Timkiem;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbtn_khoangtg;
    private javax.swing.JRadioButton rbtn_ma;
    private javax.swing.JRadioButton rbtn_ngaybd;
    private javax.swing.JRadioButton rbtn_ngaykt;
    private javax.swing.JRadioButton rbtn_ten;
    private javax.swing.JTable tbl_ctkhuyenmai1;
    private javax.swing.JTable tbl_khuyenmai;
    private javax.swing.JTextField ttkm_gtkm1;
    private javax.swing.JTextField ttkm_makm4;
    private javax.swing.JTextField ttkm_makm5;
    private javax.swing.JTextField ttkm_makm6;
    private javax.swing.JTextField ttkm_makm7;
    private javax.swing.JTextField ttkm_masp1;
    public javax.swing.JTextField txt_batdau;
    public javax.swing.JTextField txt_ketthuc;
    private javax.swing.JTextField txt_ketthuc2;
    public javax.swing.JTextField txt_makm;
    private javax.swing.JTextField txt_ngaybd;
    private javax.swing.JTextField txt_ngaykt;
    public javax.swing.JTextField txt_tenkm;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
