/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;


import BUS.KhuyenMai_BUS;
import BUS.SanPham_BUS;
import DTO.KhuyenMai_DTO;
import DTO.SanPham_DTO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import BUS.CTKhuyenMai_BUS;
import DTO.CTKhuyenMai_DTO;

/**
 *
 * @author blemb
 */
public class KhuyenMai_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form KhuyenMai_GUI
     */
    public KhuyenMai_GUI() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        showAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Timkiem = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khuyenmai = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_batdau = new javax.swing.JTextField();
        txt_makm = new javax.swing.JTextField();
        txt_tenkm = new javax.swing.JTextField();
        txt_ketthuc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtn_khoangtg = new javax.swing.JRadioButton();
        rbtn_ma = new javax.swing.JRadioButton();
        rbtn_ten = new javax.swing.JRadioButton();
        rbtn_ngaybd = new javax.swing.JRadioButton();
        rbtn_ngaykt = new javax.swing.JRadioButton();
        txt_timkiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_ngaybd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ngaykt = new javax.swing.JTextField();
        btn_lammoi = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        ttkm_makm = new javax.swing.JTextField();
        ttkm_masp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ttkm_gtkm = new javax.swing.JTextField();
        btn_them1 = new javax.swing.JButton();
        btn_xoa1 = new javax.swing.JButton();
        btn_sua1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ctkhuyenmai = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1075, 600));
        setMinimumSize(new java.awt.Dimension(1075, 600));
        setPreferredSize(new java.awt.Dimension(1075, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setMaximumSize(new java.awt.Dimension(1075, 590));
        jPanel6.setMinimumSize(new java.awt.Dimension(1075, 590));
        jPanel6.setPreferredSize(new java.awt.Dimension(1075, 590));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Khuyến mãi"));

        tbl_khuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KM", "Tên KM", "Bắt đầu", "Kết thúc"
            }
        ));
        tbl_khuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khuyenmai);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 500, 300));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Khuyến mãi"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_batdau.setColumns(10);
        txt_batdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_batdauActionPerformed(evt);
            }
        });
        jPanel3.add(txt_batdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 109, -1));

        txt_makm.setColumns(3);
        jPanel3.add(txt_makm, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 24, -1, -1));

        txt_tenkm.setColumns(10);
        jPanel3.add(txt_tenkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 380, -1));

        txt_ketthuc.setColumns(10);
        txt_ketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ketthucActionPerformed(evt);
            }
        });
        jPanel3.add(txt_ketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 115, -1));

        jLabel2.setText("Tên KM:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Mã KM:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 27, -1, -1));

        jLabel4.setText("Bắt đầu:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setText("Kết thúc:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 414, 550, 190));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Timkiem.add(rbtn_khoangtg);
        rbtn_khoangtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_khoangtgActionPerformed(evt);
            }
        });
        jPanel1.add(rbtn_khoangtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 110, -1, -1));

        Timkiem.add(rbtn_ma);
        rbtn_ma.setText("Theo mã");
        jPanel1.add(rbtn_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 37, -1, -1));

        Timkiem.add(rbtn_ten);
        rbtn_ten.setText("Theo Tên");
        jPanel1.add(rbtn_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 37, -1, -1));

        Timkiem.add(rbtn_ngaybd);
        rbtn_ngaybd.setText("Ngày bắt đầu");
        jPanel1.add(rbtn_ngaybd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 69, -1, -1));

        Timkiem.add(rbtn_ngaykt);
        rbtn_ngaykt.setText("Ngày kết thúc");
        jPanel1.add(rbtn_ngaykt, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 69, -1, -1));
        jPanel1.add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 158, 155, -1));

        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 158, -1, -1));

        jLabel1.setText("Từ:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 110, -1, -1));
        jPanel1.add(txt_ngaybd, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 107, 100, -1));

        jLabel6.setText("Đến:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        jPanel1.add(txt_ngaykt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 100, -1));

        btn_lammoi.setText("Refresh");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 360, 300));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết khuyến mãi"));

        ttkm_makm.setColumns(3);

        ttkm_masp.setColumns(10);
        ttkm_masp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttkm_maspActionPerformed(evt);
            }
        });

        jLabel16.setText("Mã SP:");

        jLabel17.setText("Mã KM:");

        jLabel20.setText("KM(%):");

        ttkm_gtkm.setColumns(3);

        btn_them1.setText("Thêm");
        btn_them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_them1ActionPerformed(evt);
            }
        });

        btn_xoa1.setText("Xóa");
        btn_xoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoa1ActionPerformed(evt);
            }
        });

        btn_sua1.setText("Sửa");
        btn_sua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_them1)
                        .addGap(48, 48, 48)
                        .addComponent(btn_xoa1)
                        .addGap(48, 48, 48)
                        .addComponent(btn_sua1))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(ttkm_makm, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(12, 12, 12)
                        .addComponent(ttkm_gtkm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addComponent(ttkm_masp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ttkm_makm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttkm_masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(ttkm_gtkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_them1)
                    .addComponent(btn_xoa1)
                    .addComponent(btn_sua1))
                .addGap(18, 18, 18))
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 300, 550, 110));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết khuyến mãi"));

        tbl_ctkhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID_KM", "ID_SP", "Tên SP", "KM (%)", "Đơn giá", "Giảm còn"
            }
        ));
        tbl_ctkhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ctkhuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_ctkhuyenmai);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 300));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txt_batdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_batdauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_batdauActionPerformed

    private void txt_ketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ketthucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ketthucActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        showAll();
        showAll_ctkm();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void tbl_khuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khuyenmaiMouseClicked
        // TODO add your handling code here:
        int i = tbl_khuyenmai.getSelectedRow();
        txt_makm.setText(tbl_khuyenmai.getModel().getValueAt(i, 1).toString());
        txt_tenkm.setText(tbl_khuyenmai.getModel().getValueAt(i,2).toString());
        txt_batdau.setText(tbl_khuyenmai.getModel().getValueAt(i,3).toString());
        txt_ketthuc.setText(tbl_khuyenmai.getModel().getValueAt(i,4).toString());
        //Hiện chi tiết khuyến mãi
        CTKhuyenMai_BUS bus = new CTKhuyenMai_BUS();  
        bus.docDS_CTKM_ID(tbl_khuyenmai.getValueAt(i, 1).toString());
        DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Mã SP");
        header.add("Tên SP");
        header.add("Đơn giá");
        header.add("Giảm còn");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(CTKhuyenMai_DTO ctkm : bus.ds_ctkm){
            Vector row = new Vector();
            row.add(count);
            row.add(ctkm.id_km);
            row.add(ctkm.id_sp);
            row.add(ctkm.ten_sp);
            row.add(ctkm.giaban);
            row.add(ctkm.giamcon);
            count++;
            n.addRow(row);
        }
        tbl_ctkhuyenmai.setModel(n);
    }//GEN-LAST:event_tbl_khuyenmaiMouseClicked

    private void rbtn_khoangtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_khoangtgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_khoangtgActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String a = txt_makm.getText();
        String b = txt_tenkm.getText();
        String c = txt_batdau.getText();
        String d = txt_ketthuc.getText();
        String e = "";
        int flag = 0;
        if("".equals(a) || "".equals(b) || "".equals(c) || "".equals(d) ){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        } else {
            for(int i = 0; i < tbl_khuyenmai.getRowCount(); i++){
                if(a.equals(tbl_khuyenmai.getValueAt(i, 1)))
                    flag = 1;
            }
            if(flag != 1){
            new KhuyenMai_BUS().themKM(a, b, c, d);
            } else {
                JOptionPane.showMessageDialog(null, "Mã khuyến mãi bị trùng");
            }
        }
        showAll();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int i = tbl_khuyenmai.getSelectedRow();
        String id = tbl_khuyenmai.getValueAt(i, 1).toString();
        new KhuyenMai_BUS().xoaKM(id);
        showAll();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        //lỗi refresh
        int flag = 0;
        int i = tbl_khuyenmai.getSelectedRow();
        String id = tbl_khuyenmai.getValueAt(i, 1).toString();
        String id_new = txt_makm.getText();
        String ten = txt_tenkm.getText();
        String batdau = txt_batdau.getText();
        String ketthuc = txt_ketthuc.getText();
        for(int j = 0; j < tbl_khuyenmai.getRowCount(); j++){
            if(j != i){
                if(id_new.equals(tbl_khuyenmai.getValueAt(j, 1))){
                    flag = 1;
                }
            }
        }
        if(flag != 1){
        new KhuyenMai_BUS().suaKM(id_new, ten, batdau, ketthuc, id);
        
        }
        else JOptionPane.showMessageDialog(null, "Mã khuyến mãi đã tồn tại");
    }//GEN-LAST:event_btn_suaActionPerformed
    
    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String key_word = txt_timkiem.getText();
        if(rbtn_ten.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ten(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
        
        if(rbtn_ma.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ma(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
        if(rbtn_ngaybd.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ngaybd(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
        if(rbtn_ngaykt.isSelected()){
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_ngaykt(key_word); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }      
        if(rbtn_khoangtg.isSelected()){
            String bd = txt_ngaybd.getText();
            String kt = txt_ngaykt.getText();
            KhuyenMai_BUS bus = new KhuyenMai_BUS();
            bus.timKM_khoangtg(bd, kt); 
            DefaultTableModel n = new DefaultTableModel();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã KM");
        header.add("Tên KM");
        header.add("Bắt đầu");
        header.add("Kết thúc");
        n = new DefaultTableModel(header,0);
        int count = 0;
        for(KhuyenMai_DTO km : bus.dskm){
            Vector row = new Vector();
            row.add(count);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            count++;
            n.addRow(row);
        }
        tbl_khuyenmai.setModel(n);
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void tbl_ctkhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ctkhuyenmaiMouseClicked
        // TODO add your handling code here:
        int i = tbl_ctkhuyenmai.getSelectedRow();
        ttkm_makm.setText(tbl_ctkhuyenmai.getModel().getValueAt(i, 1).toString());
        ttkm_gtkm.setText(tbl_ctkhuyenmai.getModel().getValueAt(i,4).toString());
        ttkm_masp.setText(tbl_ctkhuyenmai.getModel().getValueAt(i,2).toString());    
    }//GEN-LAST:event_tbl_ctkhuyenmaiMouseClicked

    private void ttkm_maspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttkm_maspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttkm_maspActionPerformed

    private void btn_them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_them1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_them1ActionPerformed

    private void btn_xoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xoa1ActionPerformed

    private void btn_sua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sua1ActionPerformed
    public void showAll(){
        DefaultTableModel n = new DefaultTableModel();
        KhuyenMai_BUS bus = new KhuyenMai_BUS();
        bus.docDSKM();
        Vector header = new Vector();
            header.add("STT");
            header.add("Mã KM");
            header.add("Tên KM");
            header.add("Bắt đầu");
            header.add("Kết thúc");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (KhuyenMai_DTO km :  KhuyenMai_BUS.dskm) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(km.id_km);
            row.add(km.ten_km);
            row.add(km.batdau);
            row.add(km.ketthuc);
            n.addRow(row);
            k++;
        }
        tbl_khuyenmai.setModel(n);
    }
    public void showAll_ctkm(){
        DefaultTableModel n = new DefaultTableModel();
        CTKhuyenMai_BUS bus = new CTKhuyenMai_BUS();
        bus.docDS_CTKM();
        Vector header = new Vector();
            header.add("STT");
            header.add("ID_KM");
            header.add("ID_SP");
            header.add("Tên SP");
            header.add("KM (%)");
            header.add("Đơn giá");
            header.add("Giá sau KM");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (CTKhuyenMai_DTO ctkm : CTKhuyenMai_BUS.ds_ctkm) {

            Vector row = new Vector();
            row.add(k);
            row.add(ctkm.id_km);
            row.add(ctkm.id_sp);
            row.add(ctkm.ten_sp);
            row.add(ctkm.gtkm);
            row.add(ctkm.giaban);
            row.add(ctkm.giamcon);
            n.addRow(row);
            k++;
        }
        tbl_ctkhuyenmai.setModel(n);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Timkiem;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_sua1;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_them1;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xoa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbtn_khoangtg;
    private javax.swing.JRadioButton rbtn_ma;
    private javax.swing.JRadioButton rbtn_ngaybd;
    private javax.swing.JRadioButton rbtn_ngaykt;
    private javax.swing.JRadioButton rbtn_ten;
    private javax.swing.JTable tbl_ctkhuyenmai;
    private javax.swing.JTable tbl_khuyenmai;
    private javax.swing.JTextField ttkm_gtkm;
    private javax.swing.JTextField ttkm_makm;
    private javax.swing.JTextField ttkm_masp;
    public javax.swing.JTextField txt_batdau;
    public javax.swing.JTextField txt_ketthuc;
    public javax.swing.JTextField txt_makm;
    private javax.swing.JTextField txt_ngaybd;
    private javax.swing.JTextField txt_ngaykt;
    public javax.swing.JTextField txt_tenkm;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
