/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import BUS.CTPhieuNhap_BUS;
import BUS.PhieuNhap_BUS;
import BUS.SanPham_BUS;
import DTO.CTPhieuNhap_DTO;
import DTO.PhieuNhap_DTO;
import DTO.SanPham_DTO;
import java.util.Vector;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author blemb
 */
public class NhapHang_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form NhapHang_GUI
     */
    public NhapHang_GUI() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        showAll_PN();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_mapn = new javax.swing.JTextField();
        txt_mancc = new javax.swing.JTextField();
        txt_ngaynhap = new javax.swing.JTextField();
        txt_manv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_xoa = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        txt_masp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ctphieunhap = new javax.swing.JTable();
        pn_phieunhap = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_phieunhap = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1075, 590));
        setMinimumSize(new java.awt.Dimension(1075, 590));
        setPreferredSize(new java.awt.Dimension(1075, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jRadioButton2.setText("Mã PN");

        jRadioButton3.setText("Mã NCC");

        jRadioButton6.setText("Ngày nhập");

        jRadioButton7.setText("Mã NV");

        jTextField1.setColumns(5);

        jButton4.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton7))
                        .addGap(53, 53, 53)
                        .addComponent(jRadioButton3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jRadioButton6)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 390, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_mapn.setText("ID_PN");
        jPanel3.add(txt_mapn, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 48, -1, -1));

        txt_mancc.setText("MaNCC");
        jPanel3.add(txt_mancc, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 48, 140, -1));

        txt_ngaynhap.setText("NgayNhap");
        jPanel3.add(txt_ngaynhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 130, -1));

        txt_manv.setText("MaNV");
        jPanel3.add(txt_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 103, 110, -1));

        jLabel1.setText("Mã PN:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 51, -1, -1));

        jLabel2.setText("Mã NCC:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 51, -1, -1));

        jLabel3.setText("Ngày Nhập:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel4.setText("Mã NV: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 106, -1, -1));

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel3.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        txt_masp.setText("MaNCC");
        jPanel3.add(txt_masp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 140, -1));

        jLabel5.setText("Mã SP:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        txt_soluong.setText("MaNCC");
        jPanel3.add(txt_soluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 140, -1));

        jLabel6.setText("Số lượng:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 640, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết phiếu nhập"));

        tbl_ctphieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã PN", "Mã SP", "Số lượng"
            }
        ));
        tbl_ctphieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ctphieunhapMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_ctphieunhap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 260));

        pn_phieunhap.setBorder(javax.swing.BorderFactory.createTitledBorder("Phiếu nhập"));

        tbl_phieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã PN", "Mã NCC", "Ngày nhập", "Mã NV"
            }
        ));
        tbl_phieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_phieunhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_phieunhap);
        if (tbl_phieunhap.getColumnModel().getColumnCount() > 0) {
            tbl_phieunhap.getColumnModel().getColumn(3).setHeaderValue("Ngày nhập");
        }

        javax.swing.GroupLayout pn_phieunhapLayout = new javax.swing.GroupLayout(pn_phieunhap);
        pn_phieunhap.setLayout(pn_phieunhapLayout);
        pn_phieunhapLayout.setHorizontalGroup(
            pn_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        pn_phieunhapLayout.setVerticalGroup(
            pn_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        getContentPane().add(pn_phieunhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 380, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showAll_PN(){
        DefaultTableModel n = new DefaultTableModel();
        PhieuNhap_BUS bus = new PhieuNhap_BUS();
        bus.docDSPN();
        Vector header = new Vector();
            header.add("STT");
            header.add("Mã PN");
            header.add("Mã NCC");
            header.add("Ngày nhập");
            header.add("Mã NV");
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (PhieuNhap_DTO pn : PhieuNhap_BUS.dspn) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(pn.id_phieunhap);
            row.add(pn.id_ncc);
            row.add(pn.ngaynhap);
            row.add(pn.id_nhanvien);
            n.addRow(row);
            k++;
        }
        tbl_phieunhap.setModel(n);
    }
    public void showAll_CTPN(){
        DefaultTableModel n = new DefaultTableModel();
        CTPhieuNhap_BUS bus = new CTPhieuNhap_BUS();
        bus.docDS_CTKM();
        Vector header = new Vector();
            header.add("STT");
            header.add("Mã PN");
            header.add("Mã SP");
            header.add("Số lượng");
            
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (CTPhieuNhap_DTO ctpn : CTPhieuNhap_BUS.ds_ctpn) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(ctpn.id_phieunhap);
            row.add(ctpn.id_sp);
            row.add(ctpn.soluong);
            
            n.addRow(row);
            k++;
        }
        tbl_ctphieunhap.setModel(n);
    }
    private void tbl_phieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_phieunhapMouseClicked
        // TODO add your handling code here:
        txt_masp.setVisible(false);
        txt_soluong.setVisible(false);
        
        txt_manv.setVisible(true);
        txt_mancc.setVisible(true);
        txt_ngaynhap.setVisible(true);
        int i = tbl_phieunhap.getSelectedRow();
        DefaultTableModel n = new DefaultTableModel();
        CTPhieuNhap_BUS bus = new CTPhieuNhap_BUS();
        bus.docDS_CTPN_ID(tbl_phieunhap.getValueAt(i, 1).toString());
        Vector header = new Vector();
            header.add("STT");
            header.add("Mã PN");
            header.add("Mã SP");
            header.add("Số lượng");
            
            n = new DefaultTableModel(header,0);
            int k = 0;
        for (CTPhieuNhap_DTO ctpn : CTPhieuNhap_BUS.ds_ctpn_id) {
     
            Vector row = new Vector();
            row.add(k);
            row.add(ctpn.id_phieunhap);
            row.add(ctpn.id_sp);
            row.add(ctpn.soluong);
            
            n.addRow(row);
            k++;
        }
        tbl_ctphieunhap.setModel(n);
        
        txt_mapn.setText(tbl_phieunhap.getValueAt(i, 1).toString());
        txt_mancc.setText(tbl_phieunhap.getValueAt(i, 2).toString());
        txt_ngaynhap.setText(tbl_phieunhap.getValueAt(i, 3).toString());
        txt_manv.setText(tbl_phieunhap.getValueAt(i, 4).toString());
        
    }//GEN-LAST:event_tbl_phieunhapMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        String id_sp = txt_mapn.getText();
        int row = tbl_phieunhap.getModel().getRowCount();
        for(int i = 0; i < row; i++){
            if(id_sp.equals(tbl_phieunhap.getValueAt(i, 1).toString())){
                flag = 1;
            }
        }
        if(flag == 0){
            String ma_sp = txt_mapn.getText();
            String ma_loai = txt_mancc.getText();
            String ma_ncc = txt_ngaynhap.getText();
            String ten_sp = txt_manv.getText();
            String mo_ta = txt_mota.getText();
            String gia = txt_gia.getText();
            String sl = txt_soluong.getText();
            new SanPham_BUS().them_sp(ma_sp, ma_loai, ma_ncc, ten_sp, mo_ta, gia, sl);
            JOptionPane.showMessageDialog(null, "Thêm sản phẩm thành công !");
            showAll();
        }else JOptionPane.showMessageDialog(null, "Mã sản phẩm đã tồn tại !");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int i = tbl_phieunhap.getSelectedRow();
        String id_sp = tbl_phieunhap.getValueAt(i, 1).toString();
        new SanPham_BUS().xoa_sp(id_sp);
        showAll();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int i = tbl_phieunhap.getSelectedRow();
        String ma_sp = txt_mapn.getText();
        String ma_loai = txt_mancc.getText();
        String ma_ncc = txt_ngaynhap.getText();
        String ten_sp = txt_manv.getText();
        String mo_ta = txt_mota.getText();
        String gia = txt_gia.getText();
        String sl = txt_soluong.getText();
        new SanPham_BUS().sua_sp(ma_sp, ma_loai, ma_ncc, ten_sp, mo_ta, gia, sl);
        showAll();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void tbl_ctphieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ctphieunhapMouseClicked
        // TODO add your handling code here:
        txt_masp.setVisible(true);
        txt_soluong.setVisible(true);
        txt_manv.setVisible(false);
        txt_mancc.setVisible(false);
        txt_ngaynhap.setVisible(false);
        int i = tbl_ctphieunhap.getSelectedRow();
        
        
        txt_mapn.setText(tbl_ctphieunhap.getValueAt(i, 1).toString());
        txt_masp.setText(tbl_ctphieunhap.getValueAt(i, 2).toString());
        txt_soluong.setText(tbl_ctphieunhap.getValueAt(i, 3).toString());
        
    }//GEN-LAST:event_tbl_ctphieunhapMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pn_phieunhap;
    private javax.swing.JTable tbl_ctphieunhap;
    private javax.swing.JTable tbl_phieunhap;
    private javax.swing.JTextField txt_mancc;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_mapn;
    private javax.swing.JTextField txt_masp;
    private javax.swing.JTextField txt_ngaynhap;
    private javax.swing.JTextField txt_soluong;
    // End of variables declaration//GEN-END:variables
}
